
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module PulseGenerator(
	
	input reset,
	input clock,
	input enable,
	input [25:0]divideby,
	output reg  go,
	input [9:4] SW,
	output reg [25:0] count,
	output reg [9:0]	LEDR,
	input MAX10_CLK1_50
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
//reg[5:0] count;
reg[25:0] count_c;
wire[25:0] maxcount;


assign maxcount=divideby-1; 
//=======================================================
//  Structural coding
//=======================================================


initial begin
count=26'b00_0000_0000_0000_0000_0000_0000;
end
always@(*)begin
	count_c=count;
	go=0;
	if(count==26'b00_0000_0000_0000_0000_0000_0000)begin
	go=1;
	end
	if(count!=maxcount)begin
		count_c=count+26'b00_0000_0000_0000_0000_0000_0001;
	end
	else begin
		count_c=26'b00_0000_0000_0000_0000_0000_0000;
	end
	/*
	if(go==1)begin
		LEDR[0]=1;
	end
	*/
	if(enable==0)begin
		count_c=count;
	end
	if(divideby==26'b00_0000_0000_0000_0000_0000_0000)begin
		go=0;
		count_c=count;
	end
	
	if((divideby!=26'b00_0000_0000_0000_0000_0000_0000)&&(count==26'b00_0000_0000_0000_0000_0000_0000))begin
	go=1;
	end
	else begin
	go=0;
	end
	
	if(reset==0)begin
		count_c=26'b00_0000_0000_0000_0000_0000_0000;
	end
end

always@(posedge clock)begin
	count<=#1 count_c;
end

endmodule
